/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_vt_cbil_visda_comp_DRMCore */

#ifndef _Included_edu_vt_cbil_visda_comp_DRMCore
#define _Included_edu_vt_cbil_visda_comp_DRMCore
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_vt_cbil_visda_comp_DRMCore
 * Method:    vePCA
 * Signature: (II[D[D[D[D[D[D[D)I
 */
JNIEXPORT jint JNICALL Java_edu_vt_cbil_visda_comp_DRMCore_vePCA
  (JNIEnv *, jobject, jint, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     edu_vt_cbil_visda_comp_DRMCore
 * Method:    veSubPCA
 * Signature: (II[D[D[D[D[D[D[D[D)I
 */
JNIEXPORT jint JNICALL Java_edu_vt_cbil_visda_comp_DRMCore_veSubPCA
  (JNIEnv *, jobject, jint, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     edu_vt_cbil_visda_comp_DRMCore
 * Method:    vePCAPPM
 * Signature: (II[D[D[D)I
 */
JNIEXPORT jint JNICALL Java_edu_vt_cbil_visda_comp_DRMCore_vePCAPPM
  (JNIEnv *, jobject, jint, jint, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     edu_vt_cbil_visda_comp_DRMCore
 * Method:    veSubPCAPPM
 * Signature: (II[D[D[D[D[D[D[D[D[D)I
 */
JNIEXPORT jint JNICALL Java_edu_vt_cbil_visda_comp_DRMCore_veSubPCAPPM
  (JNIEnv *, jobject, jint, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
