/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_vt_cbil_visda_comp_CFMCore */

#ifndef _Included_edu_vt_cbil_visda_comp_CFMCore
#define _Included_edu_vt_cbil_visda_comp_CFMCore
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_vt_cbil_visda_comp_CFMCore
 * Method:    veCov
 * Signature: (II[D[D[DD)I
 */
JNIEXPORT jint JNICALL Java_edu_vt_cbil_visda_comp_CFMCore_veCov
  (JNIEnv *, jobject, jint, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdouble);

/*
 * Class:     edu_vt_cbil_visda_comp_CFMCore
 * Method:    veModel
 * Signature: (III[D[D[D[D[D[D)I
 */
JNIEXPORT jint JNICALL Java_edu_vt_cbil_visda_comp_CFMCore_veModel
  (JNIEnv *, jobject, jint, jint, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     edu_vt_cbil_visda_comp_CFMCore
 * Method:    veSubEM
 * Signature: (III[D[D[DD[D[D[D[D)I
 */
JNIEXPORT jint JNICALL Java_edu_vt_cbil_visda_comp_CFMCore_veSubEM
  (JNIEnv *, jobject, jint, jint, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdouble, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
