/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_vt_cbil_visda_view_VeVisT */

#ifndef _Included_edu_vt_cbil_visda_view_VeVisT
#define _Included_edu_vt_cbil_visda_view_VeVisT
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_vt_cbil_visda_view_VeVisT
 * Method:    csort
 * Signature: (I[D[IC)I
 */
JNIEXPORT jint JNICALL Java_edu_vt_cbil_visda_view_VeVisT_csort
  (JNIEnv *, jobject, jint, jdoubleArray, jintArray, jchar);

#ifdef __cplusplus
}
#endif
#endif
