/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_vt_cbil_visda_comp_FeaturePreSelector */

#ifndef _Included_edu_vt_cbil_visda_comp_FeaturePreSelector
#define _Included_edu_vt_cbil_visda_comp_FeaturePreSelector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_vt_cbil_visda_comp_FeaturePreSelector
 * Method:    veSNR
 * Signature: (II[D[II[I[D)I
 */
JNIEXPORT jint JNICALL Java_edu_vt_cbil_visda_comp_FeaturePreSelector_veSNR
  (JNIEnv *, jobject, jint, jint, jdoubleArray, jintArray, jint, jintArray, jdoubleArray, jint, jdoubleArray, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
